ccflags-y += -I$(srctree)/google-modules/display/common/include

ccflags-y += -I$(srctree)/google-modules/bms
ccflags-y += -I$(srctree)/google-modules/display/samsung
ccflags-y += -I$(srctree)/google-modules/display/samsung/cal_common
ccflags-y += -I$(srctree)/google-modules/display/samsung/include/uapi
ccflags-y += -I$(srctree)/google-modules/soc/gs/include

obj-m += panel-gs-cm4.o
obj-m += panel-gs-km4.o
obj-m += panel-gs-tk4a.o
obj-m += panel-gs-tk4b.o
obj-m += panel-gs-tk4c.o

obj-m += exposure-adj.o
